### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by mimotej** [example-test-organization/support#20]
### Target cluster

Smaug

### Target environment

emea

### Team name

sams-team

### Desired project names

sams-namespace

### Project Owner

SamoKopecky

### Project description

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vulputate sapien nec sagittis aliquam malesuada bibendum. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. In fermentum posuere urna nec. Nullam vehicula ipsum a arcu cursus. Magna eget est lorem ipsum. Egestas sed sed risus pretium quam vulputate dignissim suspendisse. Lectus quam id leo in. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Sapien nec sagittis aliquam malesuada. Adipiscing enim eu turpis egestas pretium. Hendrerit dolor magna eget est lorem ipsum dolor.

Dolor morbi non arcu risus quis varius quam. Diam phasellus vestibulum lorem sed. Dis parturient montes nascetur ridiculus. Donec ultrices tincidunt arcu non sodales. Amet luctus venenatis lectus magna fringilla urna porttitor. Ipsum dolor sit amet consectetur adipiscing. Integer enim neque volutpat ac tincidunt vitae semper. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Tempus egestas sed sed risus pretium quam vulputate. Odio euismod lacinia at quis risus sed vulputate odio. Bibendum enim facilisis gravida neque convallis a. Consequat semper viverra nam libero justo laoreet sit amet. Habitant morbi tristique senectus et netus et malesuada. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Id porta nibh venenatis cras sed felis eget velit aliquet. Ullamcorper dignissim cras tincidunt lobortis feugiat.

Nisi porta lorem mollis aliquam ut porttitor leo a. Ut venenatis tellus in metus vulputate eu scelerisque. Tellus rutrum tellus pellentesque eu. In aliquam sem fringilla ut morbi tincidunt augue interdum. Diam ut venenatis tellus in. Risus nullam eget felis eget nunc lobortis mattis. Sed risus pretium quam vulputate dignissim suspendisse in est. Habitant morbi tristique senectus et netus. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Enim praesent elementum facilisis leo vel fringilla. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Ut etiam sit amet nisl purus in mollis nunc. Convallis tellus id interdum velit laoreet id. Dictum non consectetur a erat nam. Facilisi morbi tempus iaculis urna id volutpat lacus. Sagittis orci a scelerisque purus semper eget

### Link to project documentation

https://example.com/

### Users needing access

SamoKopecky

### Namespace Quota

Medium

**Comment by HumairAK** [comment]
@mimotej the sample `apps` repo's `cluster-scope` directory wasn't a full imitation of the `operate-first/apps/cluster-scope` directory, it initially only had `smaug` overlay, I've added the `infra` overlay, and done a retry. See logs for previous attempts that failed here: https://console-openshift-console.apps.smaug.na.operate-first.cloud/pipelines/ns/robozome/pipeline-runs
