### ISSUE TITLE
NEW PROJECT: Sams project2

### ISSUE THREAD

**Issue by SamoKopecky** [example-test-organization/support#21]
### Target cluster

Smaug

### Target environment

emea

### Team name

sams-team

### Desired project names

sams-namespace

### Project Owner

SamoKopecky

### Project description

Lorem ipsum dolor sit amet

### Link to project documentation

https://example.com/

### Users needing access

SamoKopecky

### Namespace Quota

Medium

**Comment by HumairAK** [comment]
@SamoKopecky see [this comment](https://github.com/example-test-organization/support/issues/20#issuecomment-1305917715) for why this failed and how to inspect the issues.  You can retry by typing `/ robozome retry`.

custom quota is not yet supported though, that would be one of the next items on the list, atm only specified quotas are possible, so it will fail again. I'd update it to use a specific quota tier before retrying. Add custom quota support by updating the script [here](https://github.com/operate-first/apps/blob/master/scripts/onboarding.sh)

**Comment by HumairAK** [comment]
looks like the [parser](https://github.com/operate-first/probot-extensions/blob/main/packages/probot-issue-form/parser.ts) is returning an empty data object after you edited the form, I'll have to take a look to see why, maybe manual updates after the form is created is not supported ?
